### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by bertinho79** [bytestorm/ecoforest_ecogeo#1]
Hi!,

      Sorry but to try add this repo on HACS tell me when i try download "The version 5461f26 for this integration can not be used with HACS."

**Comment by bertinho79** [comment]
@bytestorm can you review this error? Or if you need me to provide you with any further information, let me know. Because I really find this integration very interesting.

**Comment by bytestorm** [comment]
@bertinho79 could you please tell me your HACS and HA versions? I have no issues installing/running it with the latest ones

**Comment by bertinho79** [comment]
@bytestorm 
![image](https://github.com/user-attachments/assets/920e7448-40b5-493a-bd3d-6d9be2a42b7f)
![image](https://github.com/user-attachments/assets/431a0313-4ea2-4e52-854f-426b24be5ac5)
![image](https://github.com/user-attachments/assets/aabca2ea-7d3c-4fc9-b8e3-169fd8c0eb5a)

**Comment by bytestorm** [comment]
it appears I had an older version of HACS, will look into this later today

**Comment by bytestorm** [comment]
@bertinho79 should be fine now

**Comment by bertinho79** [comment]
@bytestorm thanks! it´s perfect. Now to configure. On the second line is IP on the third is password but on the first?

**Comment by bytestorm** [comment]
Looks like translations went rogue too. Fixed. You may need to clear your browser cache after updating. These fields are: ecoforest URL, username and password

**Comment by bertinho79** [comment]
@bytestorm perfect it worked! now to can the custom power flow card is copy code and paste in new file with extension .yaml? and put it on?

**Comment by bytestorm** [comment]
@bertinho79 no, you need to install https://github.com/flixlix/power-flow-card-plus using HACS
Then you'll need to add power flow card to your dashboard and use my code in code editor (or manually configure it to your liking)

**Comment by bertinho79** [comment]
@bytestorm thanks again! Little by little it is taking shape. Now I can see the water temperature, but the other markers are set to zero.
![image](https://github.com/user-attachments/assets/4235b7f8-640c-4ee4-85da-3cbd13db4d06)
![image](https://github.com/user-attachments/assets/017a0878-6a3c-461f-9f29-14397168ee2f)

**Comment by bytestorm** [comment]
@bertinho79 most likely, you have a slightly different heat pump than mine.
I know there are at least 4 different versions, but I only have access to one for obvious reasons =)
We could try checking yours out during some weekend. They're relatively easy to reverse engineer to implement whatever is needed.

**Comment by bertinho79** [comment]
Sería estupendo! No se si tienes telegram y seguimos en contacto por ahí. Te paso mi telegram:                          ***@***.***                   El 20 sept 2024 15:46, Sasha Boyko ***@***.***> escribió:
@bertinho79 most likely, you have a slightly different heat pump than mine.
I know there are at least 4 different versions, but I only have access to one for obvious reasons =)
We could try checking yours out during some weekend. They're relatively easy to reverse engineer to implement whatever is needed.

**Comment by bertinho79** [comment]
It would be great! I don't know if you have telegram and we keep in touch.I'll pass my telegram:                          ***@***.*** 20 sept 2024 15:46, Sasha Boyko ***@***.***> escribió:
@bertinho79 most likely, you have a slightly different heat pump than mine.
I know there are at least 4 different versions, but I only have access to one for obvious reasons =)
We could try checking yours out during some weekend. They're relatively easy to reverse engineer to implement whatever is needed.

**Comment by Jscifu** [comment]
Hello, I am really interested also in this integration, everything went fine but after installation it I can´t see some temperatures (values are -999,9 ºC). I just updated it but I still can't see temperatures. May bee I have another boileer version.

![image](https://github.com/user-attachments/assets/5c3ff867-1bc6-45d4-815d-84ff9c82a3ee)


Can you help me with reverse ingineer?
Regards

**Comment by bytestorm** [comment]
@Jscifu looks like you've got the same heat pump model mentioned above since only DHW and outdoor temperatures are displayed properly. I've created a [separate ticket](https://github.com/bytestorm/ecoforest_ecogeo/issues/2) to implement support for other models.

@Jscifu, @bertinho79, could you please post details about your heat pump (like model, easynet versions info, anything you think might be useful) [there](https://github.com/bytestorm/ecoforest_ecogeo/issues/2)?

I'm closing this issue since it was about the new HACS version support.
