### ISSUE TITLE
Support for multiple heatpump models

### ISSUE THREAD

**Issue by bytestorm** [bytestorm/ecoforest_ecogeo#2]
If you have issues with this integration and your heat pump, please post information about your heat pump, such as software versions and heat pump models.

**Comment by Jscifu** [comment]
OK, sorry for post in the wrong thread, 
I attach heat pump information, my model is C3T 5-22KW HTR EH. 
![image](https://github.com/user-attachments/assets/a5375c99-9fd5-4e5e-94d3-68632567c4d9)

I am not sure about easynet versión, from ecoforesthome, I can see this information:

![image](https://github.com/user-attachments/assets/bc0f9aa0-40b1-46b6-b0a3-29f805dd10be)

**Comment by bytestorm** [comment]
@Jscifu ok, I have a bit newer software and a little different heat pump (mine is B4T 5-22KW HTR EH), so it should be easy to deal with.

Please DM me on Discord so we can have a better way of communicating. My discord username is bytest0rm

**Comment by bertinho79** [comment]
Hi, sorry for the delay. The integration is going well for me, those values ​​that I did not put are simply because the boiler was not having consumption because the water was already hot hahaha, so everything is perfect. Great job! 
Later I will show you the boiler model I have, but it is a geothermal boiler.

**Comment by rholighaus** [comment]
I have successfully integrated one of my two Ecogeo heatpumps.
When trying to add a second integration, I get an error message (something like "already exists", even though IP address is different.

**Comment by bytestorm** [comment]
@rholighaus let me guess... are they the same model?

**Comment by rholighaus** [comment]
yes they are - sorry about that.
But their easynet boxes obviously have a different IP address.

**Comment by bytestorm** [comment]
@rholighaus I've been using the heat pump model to create unique device identifiers in HA (since I couldn't find any serial numbers in easynet), which explains why you're getting this error.
I could add an ability to specify an alias during the configuration step, but I'll need help with testing since I only own a single unit =)

**Comment by rholighaus** [comment]
Happy to test that for you!

**Comment by rholighaus** [comment]
@bytestorm I would very much like to get my second heatpump into HA.
Please let me know how I can assist/contribute.

**Comment by bytestorm** [comment]
@rholighaus I've added an ability to specify device alias in https://github.com/bytestorm/ecoforest_ecogeo/commit/f297192c4db164af23da8e68a147e1ced051c165. Please check if it works for you

**Comment by rholighaus** [comment]
Works very well. Thank you soooooooo much!!!!!

You may want to name the entities according to the Alias (instead of "Ecoforest") so the entity name reflects the heatpump.
 
**Wishlist:** 
It would be cool if you could also incorporate these data points (from Ecoforest's Modbus description, see attachment):

Sensors:
       1 TIP Brine oulet temperature Analog
       2 TRP Brine inlet temperature Analog
       8 DHW temperature Analog
       13 Brine circuit pressure Analog
       14 Heating circuit pressure  Analog
       30 COP Analog
       31 PF Analog        

Switches:
       5222 BUS DHW Demand Integer 0/1 R/W (should switch the DHW circulation pump)
       5223 BUS Pool Demand Integer 0/1 R/W  (should switch the Pool circulation pump)

And even better would be to allow the reading/setting of

       134 BUS DHW Setpoint Analog R/W (target hot water temp, 64.5° would have to be sent as 645)
       143 BUS Pool Setpoint  Analog R/W (target pool temp, see above for format of temperature)

These are all according to my modbus manual from Ecoforest which I attach to this comment. I noticed it doesn't completely match your csv file.

[Modbus-2021_EN_v02.pdf](https://github.com/user-attachments/files/17444833/Modbus-2021_EN_v02.pdf)

**Comment by bytestorm** [comment]
@rholighaus yeah, I have this manual too. I could never find/compile a proper list of registers, so I stored the one with the most to edit later.

> You may want to name the entities according to the Alias (instead of "Ecoforest") so the entity name reflects the heatpump.
That makes sense, will make it work this way.

Regarding the new sensors/switches - it would be better to create a separate issue/issues with these requests so it won't be "everything in one place", since some of these parameters are "1 minute to implement", but some might require a bit of refactoring to make it work

**Comment by bytestorm** [comment]
@rholighaus 

> 1 TIP Brine oulet temperature Analog
> 2 TRP Brine inlet temperature Analog
> 8 DHW temperature Analog
> 13 Brine circuit pressure Analog
> 14 Heating circuit pressure Analog
> 30 COP Analog
> 31 PF Analog

these are now available in https://github.com/bytestorm/ecoforest_ecogeo/commit/5bbd73cda82ef665b2d2abde8dc116aede1084de (mind that T DHW was available even before).

**Comment by bytestorm** [comment]
> You may want to name the entities according to the Alias (instead of "Ecoforest") so the entity name reflects the heatpump.

https://github.com/bytestorm/ecoforest_ecogeo/commit/776ed94552b48dfdbac7eafe87b9e4194fc787ec now does that.

Closing this issue, please report issues/ask for features separately or in the relevant topics.
