### ISSUE TITLE
Error messages?

### ISSUE THREAD

**Issue by rholighaus** [bytestorm/ecoforest_ecogeo#3]
These error messages are in my logfile. Maybe they help you?
Please let me know if I can help debug.

Cheers
Ralf.

Logger: custom_components.ecoforest_ecogeo.overrides.api
Source: custom_components/ecoforest_ecogeo/overrides/api.py:152
integration: Ecoforest Ecogeo (documentation, issues)
First occurred: 10:38:03 (38 occurrences)
Last logged: 10:55:41

{3: '0181', 4: '0176', 5: '0156', 6: '0088', 7: '00C3', 8: '01C1', 9: '0000', 10: '0000', 11: '0063', 105: '1', 106: '1', 107: '1', 194: '013E', 195: '00D7', 196: 'D8F1', 197: '0181', 198: '01AE', 199: '00CD', 200: '01BF', 201: '00C6', 5066: '014F', 5067: '000A', 5068: '0000', 5069: '0000', 5070: '0000', 5071: '0000', 5072: '0000', 5073: '0000', 5074: '0000', 5075: '0000', 5076: '0000', 5077: '0000', 5078: '0000', 5079: '0000', 5080: '0130', 5081: '0002', 5082: '0000', 5083: '0000', 5185: '0000', 5323: '000F', 5324: '000C', 5325: '000F', 5326: '000D', 5327: '0001', 5328: '0001'}
{3: '0181', 4: '0176', 5: '0156', 6: '0089', 7: '00C2', 8: '01C1', 9: '0000', 10: '0000', 11: '0063', 105: '1', 106: '1', 107: '1', 194: '013E', 195: '00D7', 196: 'D8F1', 197: '0181', 198: '01AE', 199: '00CD', 200: '01BF', 201: '00C6', 5066: '014F', 5067: '000A', 5068: '0000', 5069: '0000', 5070: '0000', 5071: '0000', 5072: '0000', 5073: '0000', 5074: '0000', 5075: '0000', 5076: '0000', 5077: '0000', 5078: '0000', 5079: '0000', 5080: '0130', 5081: '0002', 5082: '0000', 5083: '0000', 5185: '0000', 5323: '000F', 5324: '000C', 5325: '000F', 5326: '000D', 5327: '0001', 5328: '0001'}
{3: '0180', 4: '0175', 5: '0156', 6: '0089', 7: '00C1', 8: '01C1', 9: '0000', 10: '0000', 11: '0063', 105: '1', 106: '1', 107: '1', 194: '013E', 195: '00D7', 196: 'D8F1', 197: '0181', 198: '01AE', 199: '00CD', 200: '01BF', 201: '00C6', 5066: '014F', 5067: '000A', 5068: '0000', 5069: '0000', 5070: '0000', 5071: '0000', 5072: '0000', 5073: '0000', 5074: '0000', 5075: '0000', 5076: '0000', 5077: '0000', 5078: '0000', 5079: '0000', 5080: '0130', 5081: '0002', 5082: '0000', 5083: '0000', 5185: '0000', 5323: '000F', 5324: '000C', 5325: '000F', 5326: '000D', 5327: '0001', 5328: '0001'}
{3: '0180', 4: '0175', 5: '0156', 6: '0089', 7: '00C1', 8: '01C1', 9: '0000', 10: '0000', 11: '0063', 105: '1', 106: '1', 107: '1', 194: '013E', 195: '00D7', 196: 'D8F1', 197: '0180', 198: '01AE', 199: '00CE', 200: '01BF', 201: '00C6', 5066: '014F', 5067: '000A', 5068: '0000', 5069: '0000', 5070: '0000', 5071: '0000', 5072: '0000', 5073: '0000', 5074: '0000', 5075: '0000', 5076: '0000', 5077: '0000', 5078: '0000', 5079: '0000', 5080: '0130', 5081: '0002', 5082: '0000', 5083: '0000', 5185: '0000', 5323: '000F', 5324: '000C', 5325: '000F', 5326: '000D', 5327: '0001', 5328: '0001'}
{3: '017F', 4: '0174', 5: '0156', 6: '0089', 7: '00C0', 8: '01C0', 9: '0000', 10: '0000', 11: '0064', 105: '1', 106: '1', 107: '1', 194: '013E', 195: '00D7', 196: 'D8F1', 197: '017F', 198: '01AE', 199: '00CF', 200: '01BF', 201: '00C6', 5066: '014F', 5067: '000A', 5068: '0000', 5069: '0000', 5070: '0000', 5071: '0000', 5072: '0000', 5073: '0000', 5074: '0000', 5075: '0000', 5076: '0000', 5077: '0000', 5078: '0000', 5079: '0000', 5080: '0130', 5081: '0002', 5082: '0000', 5083: '0000', 5185: '0000', 5323: '000F', 5324: '000C', 5325: '000F', 5326: '000D', 5327: '0001', 5328: '0001'}

**Comment by rholighaus** [comment]
<img width="803" alt="screenshot" src="https://github.com/user-attachments/assets/a69c1495-51cd-47dd-a094-d78614d73d9a">

**Comment by bytestorm** [comment]
fixed in https://github.com/bytestorm/ecoforest_ecogeo/commit/f297192c4db164af23da8e68a147e1ced051c165
